spring:
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-n0ucm-kr.vpc-pub-cdb.ntruss.com:3306/Testdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: member
    password: 1q2w3e4r!