

spring:
  application:
    name: PalettePetsBack

  # spring cache => redis
  cache:
    type: redis


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.naver.com
    port: 465
    password: 1q2w3e4r!
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    username: springtest12345@naver.com
  # REDIS
  data:
    redis:
      host: 175.106.99.78
      port: 6379
      password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-n0ucm-kr.vpc-pub-cdb.ntruss.com:3306/PalettePets?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: member
    password: 1q2w3e4r!

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  #OAuth2
  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: t4zjIrqkfd1gH4oaQs24
            client-secret: sh343eKYhP
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization_grant_type: authorization_code
            scope: name,email,nickname,profile_image,gender,birthday,phone_number
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response


logging:
  level:
    com:
      zaxxer: INFO
    org:
      springframework:
        security: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug

# jwt secret Key
jwt:
  secret: sasfjkvnweor1230gfdj560912-49gflkdgj340459bjvb;l4lfo40-go5i6-sl4

server:
  port: 80


